export const TYPES = {
    IUser: Symbol.for("IUser"),
    ICountry: Symbol.for("ICountry"),
    IStore: Symbol.for("IStore"),
    ICategory: Symbol.for("ICategory"),
    IItem: Symbol.for("IItem"),
    IPackege: Symbol.for("IPackege"),
    IDeliveryAddress: Symbol.for("IDeliveryAddress"),
    IRate: Symbol.for("IRate"),
    IRegion: Symbol.for("IRegion"),
    ICity: Symbol.for("ICity"),
    UserRepository: Symbol.for("UserRepository"),
    CountryRepository: Symbol.for("CountryRepository"),
    RegionRepository: Symbol.for("RegionRepository"),
    CityRepository: Symbol.for("CityRepository"),
    UserService: Symbol.for("UserService"),
    ItemRepository: Symbol.for("ItemRepository"),
    CategoryRepository: Symbol.for("CategoryRepository"),
    PackegeRepository: Symbol.for("PackegeRepository"),
    StoreRepository: Symbol.for("StoreRepository"),
    ProductOfferRepository: Symbol.for("ProductOfferRepository"),
    OrderRepository: Symbol.for("OrderRepository"),
    DeliveryAddressRepository: Symbol.for("DeliveryAddressRepository"),
    RateRepository: Symbol.for("RateRepository"),
    ArticleRepository: Symbol.for("ArticleRepository"),
  };